version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - backend-data:/usr/src/app/data
    restart: unless-stopped
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  backend-data:
